spring:
  datasource:
    # prefix the url with `jdbc:` so that hybernate can use it
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

# made up front end client url
# if disabled websiteUrl falls back to app base ulr (see StripePaymentGateway)
# websiteUrl: https://mystore.com

# custom attribute to force swagger to use https in prod
swaggerUseSSL: true
