spring:
  datasource:
    url: jdbc:mysql://localhost:8306/store_api?createDatabaseIfNotExist=true
    username: dbuser
    password: dbpw
  jpa:
    show-sql: true # show sql statements being run

# made up front end client url
websiteUrl: http://localhost:4242
